---
driver:
  name: vagrant
  provision: false
  synced_folders:
    - ['.kitchen/cache', '/tmp/omnibus', disabled: true]

provisioner:
  name: salt_solo
  formula: usersandgroups
  salt_install: bootstrap
  salt_version: latest
  require_chef: false
  pillars:
    top.sls:
      base:
        "*":
          - usersandgroups
  state_top:
    base:
      "*":
        - usersandgroups

  # workaround to push an extra directory with ssh pub keys in the file_roots path
  dependencies:
    - name: ssh_keys
      path: ./test/salt

verifier:
  name: inspec

platforms:
  - name: debian/jessie64
  - name: debian/stretch64

suites:
  - name: default
    provisioner:
      pillars-from-files:
        usersandgroups.sls: test/salt/default/pillar/usersandgroups.sls
    verifier:
      inspec_tests:
        - path: test/integration/default
