sudo: required
cache: bundler
language: ruby

services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: default-debian-9
    - INSTANCE: default-debian-8

script:
  - bundle exec kitchen verify ${INSTANCE}

